### ISSUE TITLE
Cache the entire node_modules

### ISSUE THREAD

**Issue by JaneJeon** [JaneJeon/blink#426]
I just noticed that despite caching ~/.npm, CircleCI is *still* downloading Firefox and Chrome!

```yml

- restore_cache:
        keys:
          - v1-deps-{{ checksum "package-lock.json" }}
    - run: npm install
    - save_cache:
        key: v1-deps-{{ checksum "package-lock.json" }}
        paths:
          - node_modules

```
