### ISSUE TITLE
Too Many Redirects

### ISSUE THREAD

**Issue by joe-eklund** [JaneJeon/blink#742]
Greetings-

I am attempt to deploy this into production and getting `ERR_TOO_MANY_REDIRECTS` when I attempt to go to the homepage in my browser. 

I am deploying to a Docker Swarm cluster behind an HA Proxy load balancer. Do you have any thoughts on how to fix this? Here is my docker stack file:

```
version: '3.7'

services:
  blink:
    container_name: blink
    image: ghcr.io/janejeon/blink:latest
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
    networks:
      - blink_internal
    ports:
      - 3000:3000
    #command: npm run db:migrate
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /blink/certs:/certs
    environment:
      NODE_EXTRA_CA_CERTS: /certs/ca-bundle.crt
      PORT: 3000
      DATABASE_URL: postgres://knex@postgres/blink
      REDIS_URL: redis
      AUTO_MIGRATE: 1
      AUTO_SEED: 0

      # Backend Config
      HOMEPAGE: https://bit-app-pre.<my_domain>.tld
      BASE_URL: https://bit-pre.<my_domain>.tld

      ## Set to true/false to trust proxy according to https://github.com/jshttp/proxy-addr:
      ## true means taking the leftmost åddress of X-Forwarded-For (XFF);
      ## false means taking the remote address;
      ## a string means comma-delimited list of trusted proxy addresses;
      ## there are 3 pre-configured subnet names:
      ## - loopback - 127.0.0.1/8, ::1/128
      ## - linklocal - 169.254.0.0/16, fe80::/10
      ## - uniquelocal - 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, fc00::/7
      #TRUST_PROXY: 'true' #'loopback,linklocal,uniquelocal'

      SESSION_DURATION: '9 hours'
      SESSION_SECRET: <something_secret>

      ## This is a shorter term rate limit, meant to account for "bursty" request patterns
      RATE_LIMIT_SHORT_WINDOW: '1 min'
      RATE_LIMIT_SHORT_MAX: 100

      ## This is the longer term rate limit, meant to generally limit the abuse of authentication and APIs
      RATE_LIMIT_LONG_WINDOW: '15 min'
      RATE_LIMIT_LONG_MAX: 200

      ## How long to wait before the backend gives up scraping a link
      LINK_TIMEOUT: '15 seconds'

      ## How long the cache should last for a redirect/301
      CACHE_MAX_AGE: '10 years'

      ## OIDC/Session Config - customize this to fit with your identity provider.
      OIDC_CLIENT_ID: <some_id>
      OIDC_ISSUER_BASE_URL: 'https://my_oidc_issuer.tld/openid'
      OIDC_HTTP_TIMEOUT: '15 seconds'

      ## OAuth2 Config for API access to Blink; disable if you don't use this
      OAUTH2_ENABLED: 'true'
      OAUTH2_JWT_ALGORITHMS: 'RS256'
      OAUTH2_JWT_AUDIENCE: ''
      OAUTH2_JWT_ISSUER: ''
      OAUTH2_JWT_SECRET: <something_secret>

      ### You can either specify a static secret or dynamically load the secret to the JWT token using JWKS.
      ### Setting OAUTH2_JWT_SECRET will use static secret, otherwise it will use dynamic secrets (recommended).
      #OAUTH2_JWKS_URI: ''
      #OAUTH2_JWKS_HTTP_TIMEOUT: '15 seconds'
      #OAUTH2_JWKS_REQUESTS_PER_MINUTE: '10'

      ## This will determine the default scope assigned to OAuth2 tokens
      OAUTH2_DEFAULT_SCOPE: 'user:create user:read link:*'

      # Frontend config
      REACT_APP_BASE_URL: $BASE_URL
  
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
    #ports:
    #  - 5432:5432
    environment:
      # keep this in sync w/ DATABASE_URL in your environment file/variable
      POSTGRES_DB: blink
      POSTGRES_USER: knex
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - /blink/postgres:/var/lib/postgresql/data
    networks:
      - blink_internal
  
  redis:
    container_name: redis
    image: redis:7-alpine
    #ports:
    #  - 6379:6379
    networks:
      - blink_internal

networks:
  blink_internal:
    attachable: true
```

Blink docker logs:

```
{"level":30,"time":1654553182940,"pid":7,"hostname":"4d2fe4788db5","msg":"Starting server under production environment..."}
{"level":30,"time":1654553182941,"pid":7,"hostname":"4d2fe4788db5","msg":"Setting up DB..."}
{"level":30,"time":1654553183017,"pid":7,"hostname":"4d2fe4788db5","msg":"Connected to OIDC issuer"}
{"level":30,"time":1654553183028,"pid":7,"hostname":"4d2fe4788db5","msg":"Successfully set up DB. Starting server..."}
{"level":30,"time":1654553183029,"pid":7,"hostname":"4d2fe4788db5","msg":"Server listening on port 3000"}
```

I attempted to set more verbose logging by setting `LOG_LEVEL` in the blink environment variable section above to `debug` but that didn't seem to change any output.

I attempted to set the `HOMEPAGE` variable to `http://my_docker_node.tld:3000` and bypass my proxy and I am still getting similar behavior, so I don't think the HA Proxy is messing with it. Seems like either a Blink configuration error on my part or a bug.
