### ISSUE TITLE
Cannot start a test environment with the default compose stack provided

### ISSUE THREAD

**Issue by arnaudluti** [JaneJeon/blink#753]
Hello,

Just downloaded the docker-compose & .env files from your repo. I haven't modified the default values for database connection in .env & .yaml, except the "BASE_URL" and "HOMEPAGE".

redis & postgres starts normally, but blink is crashing with this error:

```
"err":{"type":"TypeError","message":"Cannot read properties of null (reading 'includes')","stack":"TypeError: Cannot read properties of null (reading 'includes')\n    at Function.discover (/home/node/node_modules/openid-client/lib/issuer.js:143:25)\n    at Object.<anonymous> (/home/node/middlewares/passport.js:17:8)\n    at Module._compile (node:internal/modules/cjs/loader:1103:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/home/node/app.js:8:18)\n    at Module._compile (node:internal/modules/cjs/loader:1103:14)"},"msg":"Cannot read properties of null (reading 'includes')"}
```

**docker-compose.yaml**
```                                      
services:
  blink:
    image: ghcr.io/janejeon/blink:latest
    container_name: blink
    env_file:
      - .env
    depends_on:
      - postgres_blink
      - redis_blink
    networks:
      - blink_net
    ports:
      - 3000:3000
  postgres_blink:
    container_name: postgres_blink
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      # keep this in sync w/ DATABASE_URL in your environment file/variable
      POSTGRES_DB: blink
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_blink:/var/lib/postgresql/data
    networks:
      - blink_net
  redis_blink:
    container_name: redis_blink
    image: redis:7-alpine
    ports:
      - 6379:6379
    networks:
      - blink_net
networks:
  blink_net:
    name: blink_net
volumes:
  postgres_blink:
```

**& .env file**
```
The port the service runs on
PORT=3000

#The database details in the format of: dbprovider://dbusername:dbpassword@dbhost/database
DATABASE_URL=postgres://user:password@postgres_blink/blink

#Please leave this enabled for this compose
AUTO_MIGRATE=1

#Redis URL in the format of redis://redisurl
REDIS_URL=redis://redis_blink

#Page that Blink will redirect to if someone visits the root of your BASE_URL, the way that https://bit.ly redirects to https://bitly.com.
HOMEPAGE=http://[redacted.domain.nom]/app

#The URL that your links will be served from, eg: https://bit.ly
BASE_URL=http://[redacted.domain.com]

SESSION_DURATION=9 hours

#Strong randomly generated sequence of characters.
SESSION_SECRET=

## Set to true/false to trust proxy according to https://github.com/jshttp/proxy-addr:
## true means taking the leftmost åddress of X-Forwarded-For (XFF);
## false means taking the remote address;
## a string means comma-delimited list of trusted proxy addresses;
## there are 3 pre-configured subnet names:
## - loopback - 127.0.0.1/8, ::1/128
## - linklocal - 169.254.0.0/16, fe80::/10
## - uniquelocal - 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, fc00::/7
TRUST_PROXY=loopback,linklocal,uniquelocal

## This is a shorter term rate limit, meant to account for "bursty" request patterns
RATE_LIMIT_SHORT_WINDOW=1 min
RATE_LIMIT_SHORT_MAX=100

## This is the longer term rate limit, meant to generally limit the abuse of authentication and APIs
RATE_LIMIT_LONG_WINDOW=15 min
RATE_LIMIT_LONG_MAX=200

## How long to wait before the backend gives up scraping a link
LINK_TIMEOUT=15 seconds
```

Thanks!!!
